name: Release CI

on:
  release:
    types: [created]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}

      - name: Build the k8s demo app Docker image
        run: docker build . --file Dockerfile --tag juggernaut/k8s-demo-go-app:${{ github.event.release.tag_name }}

      - name: Push the k8s demo app Docker image to Docker Hub
        run: docker push juggernaut/k8s-demo-go-app:${{ github.event.release.tag_name }}

