name: Release CI

on:
  release:
    types: [created]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Checkout tools repo
        uses: actions/checkout@v2
        with:
          repository: juggernaut/k8s-demo-config
          token: ${{ secrets.K8S_DEMO_PAT }}
          path: k8s-demo-config

      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}

      - name: Build the k8s demo app Docker image
        run: docker build . --file Dockerfile --tag juggernaut/k8s-demo-go-app:${{ github.event.release.tag_name }}

      - name: Push the k8s demo app Docker image to Docker Hub
        run: docker push juggernaut/k8s-demo-go-app:${{ github.event.release.tag_name }}

      - name: Checkout k8s config repo
        uses: actions/checkout@v2
        with:
          repository: juggernaut/k8s-demo-config
          token: ${{ secrets.K8S_DEMO_PAT }}
          path: k8s-demo-config
      - name: Install kustomize
        working-directory: k8s-demo-config
        run: |
          curl -s https://raw.githubusercontent.com/kubernetes-sigs/kustomize/master/hack/install_kustomize.sh | bash
      - name: Update k8s-demo-app image tag
        env:
          RELEASE_TAG: ${{ github.event.release.tag_name }}
        working-directory: k8s-demo-config
        run: |
          ./kustomize edit set image juggernaut/k8s-demo-go-app=juggernaut/k8s-demo-go-app:$RELEASE_TAG
          git config user.name "k8s demo CI bot"
          git config user.email "<>"
          git add kustomization.yaml
          git commit -m "CI: update image tag to $RELEASE_TAG"
          git push

